version: 2.1

# -------------------------------------------------------------------------------------------------
# PIPELINE PARAMS
# -------------------------------------------------------------------------------------------------

parameters:
  cache-version:
    type: string
    default: v1

# -------------------------------------------------------------------------------------------------
# ORBS
# -------------------------------------------------------------------------------------------------

orbs:
  frontend: ornikar/frontend-orb@dev:alpha

# -------------------------------------------------------------------------------------------------
# COMMANDS
# -------------------------------------------------------------------------------------------------

commands:
  checkout-and-restore-cache:
    steps:
      - checkout
      - frontend/restore-cache: &restore-cache-params
          version: << pipeline.parameters.cache-version >>
          cache-name: dependencies

# -------------------------------------------------------------------------------------------------
# JOBS
# -------------------------------------------------------------------------------------------------

jobs:
  dependencies:
    executor: frontend/node
    steps:
      - checkout
      - frontend/dependencies:
          before-install:
            - frontend/restore-cache: *restore-cache-params
          after-install:
            - save_cache:
                key: << pipeline.parameters.cache-version >>-node12-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
                paths:
                  - node_modules
                  - '@ornikar/browserlist-config/node_modules'
                  - '@ornikar/commitlint-config/node_modules'
                  - '@ornikar/eslint-config/node_modules'
                  - '@ornikar/eslint-config-babel/node_modules'
                  - '@ornikar/eslint-config-babel-use/node_modules'
                  - '@ornikar/eslint-config-formatjs/node_modules'
                  - '@ornikar/eslint-config-node/node_modules'
                  - '@ornikar/eslint-config-react/node_modules'
                  - '@ornikar/eslint-config-typescript/node_modules'
                  - '@ornikar/eslint-config-typescript-react/node_modules'
                  - '@ornikar/intl-config/node_modules'
                  - '@ornikar/jest-config/node_modules'
                  - '@ornikar/jest-config-react/node_modules'
                  - '@ornikar/lerna-config/node_modules'
                  - '@ornikar/postcss-config/node_modules'
                  - '@ornikar/prettier-config/node_modules'
                  - '@ornikar/renovate-config/node_modules'
                  - '@ornikar/repo-config/node_modules'
                  - '@ornikar/repo-config-react/node_modules'
                  - '@ornikar/rollup-config/node_modules'
                  - '@ornikar/storybook-config/node_modules'
                  - '@ornikar/stylelint-config/node_modules'
                  - '@ornikar/webpack-config/node_modules'

  lint:
    executor: frontend/node
    steps:
      - checkout-and-restore-cache
      - frontend/lint:
          step-name: ESLint
          script: eslint
      - frontend/lint:
          step-name: Prettier JSON
          script: prettier-json

# -------------------------------------------------------------------------------------------------
# WORKFLOWS
# -------------------------------------------------------------------------------------------------

workflows:
  version: 2

  main-workflow:
    jobs:
      - dependencies

      - frontend/checks:
          cache-version: << pipeline.parameters.cache-version >>
          run-yarn-check: true
          requires:
            - dependencies

      - lint:
          requires:
            - dependencies

      # release
      - hold-release:
          type: approval
          filters:
            branches:
              only: master
      - frontend/lerna-publish:
          cache-version: << pipeline.parameters.cache-version >>
          context: npm-publish
          requires:
            - dependencies
            - frontend/checks
            - lint
            - hold-release
          filters:
            branches:
              only: master
