version: 2

jobs:
  test:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-{{ arch }}
      - run:
          name: Install dependencies
          command: yarn --prefer-offline --frozen-lockfile --ignore-engines
      - save_cache:
          key: v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Lint code
          command: yarn run lint


workflows:
  version: 2

  main-workflow:
    jobs:
      - test

